version: '3.7'
services:
  service1:
    build:
      context: /home/ubuntu/ansible/
      dockerfile: /home/ubuntu/ansible/Dockerfile
    ports:
        - target: 5000
          published: 5000
    deploy:
      replicas: 1
