version: '3.7'
services:
  service1:
    image: nathanforester/basic_movie_db:latest
    build: basic_movie_db/
    ports:
        - target: 5000
          published: 5000
    deploy:
      replicas: 2